### ISSUE TITLE
uninitialized constant ActionController::API - actionpack (4.0.0) lib/action_dispatch/routing/route_set.rb, line 69

### ISSUE THREAD

**Issue by jwarykowski** [rails-api/rails-api#102]
Hi All,

I've been trying to get an ember frontend up and running with the rails-api project. I currently have the following setup in my routes.rb file:

``` ruby
GameOn::Application.routes.draw do
 scope 'api' do
  resources :games, except: [:edit]
 end

root to: 'ember#index'
 get '*path' => 'ember#index'
end
```

When my ember FE application makes a call to `http://localhost:5000/api/games` I get the following error returned:

ActionController::RoutingError at /api/games
uninitialized constant ActionController::API
actionpack (4.0.0) lib/action_dispatch/routing/route_set.rb, line 69

``` ruby
   64             if params && params.key?(:controller)
   65               controller_param = params[:controller]
   66               controller_reference(controller_param)
   67             end
   68           rescue NameError => e
>  69             raise ActionController::RoutingError, e.message, e.backtrace if default_controller
   70           end
   71   
   72         private
   73   
   74           def controller_reference(controller_param)
```

I won't supply the backtrace, let me know if you need. The only way I have been able to fix this is to use to reset my application controller parent class back to ActionController::Base.

``` ruby
class ApplicationController < ActionController::Base
end
```

If possible can someone get back to me as to why this error is occuring? Could this be an issue with the actionpack gem?

Regards,
Jon

**Comment by Slotos** [comment]
It's still a cosmetic issue. Rails-api gem is missing from rails-api generated project's Gemfile.

**Comment by SanjayYadav90** [comment]
Same issue I am gettin..
