### ISSUE TITLE
Cannot find mailer template

### ISSUE THREAD

**Issue by trobrock** [rails-api/rails-api#147]
I create a mailer in my rails-api app, but when I try and send the mail I get:

```
ActionView::MissingTemplate: Missing template report_mailer/adjusted_quantity with "mailer". Searched in:
  * "report_mailer"
from /Users/trobrock/Sites/herer-api/vendor/gems/actionmailer-4.1.4/lib/action_mailer/base.rb:859:in `each_template'
```

Is there something I need to configure to get the templates loading properly? Where should these templates be stored?

**Comment by eebasadre20** [comment]
Hi! how did you solved that issue? I'm currently running the issue again.

**Comment by trobrock** [comment]
I believe I had to restart spring, but I have also stopped using spring since then.

**Comment by tomasgregor** [comment]
I experience the same issue.

**Comment by mkandler** [comment]
I just had the same problem -- I'd suggest looking for https://github.com/rails/spring for how to turn off Spring, then close your terminal window and restart your computer.  Maybe some redundancy but finally worked after hours of frustration for me!

**Comment by talhaobject90** [comment]
I am also having the problem with rails 5 API
```
ExampleMailer#sample_email: processed outbound mail in 22.8ms
ActionView::MissingTemplate: Missing template example_mailer/sample_email with "mailer". Searched in:
  * "example_mailer"
```
Since the api has no "views" , don't know where to put those erb file(is it really necessary?)
I tried creating an erb file in app/views/example_mailer/sample_email.erb

Any help on this please?

**Comment by swaincreates** [comment]
Ahhhh spring got me too. Glad this was here!

**Comment by DrSayre** [comment]
Has anybody else had this problem?  I believe I have removed spring completely from my app and still get this error.  I have followed the guide exactly using rails-api gem.
