### ISSUE TITLE
Property as NilClass in before_validation callback

### ISSUE THREAD

**Issue by carlesjove** [rails-api/rails-api#164]
I'm writting a simple callback to downcase a property and substitute blank spaces with underscores

```ruby
class Plan < ActiveRecord::Base
  before_validation :generate_slug
 
 private

    def generate_slug
      self.slug = name.gsub(/ /, '_').downcase
    end
end
```
Weirdly enough, this throws a `NoMethodError` for `NilClass`:

`NoMethodError: undefined method `gsub' for nil:NilClass`

However, calling `to_s` fixes the issue:

```ruby
def generate_slug
  self.slug = name.to_s.gsub(/ /, '_').downcase
end
```
Doing exactly the same in regular Rails doesn't throw this error. At this point, I haven't figured out yet what might be causing this.

**Comment by spastorino** [comment]
I'm closing this as stale, please verify again latest versions and in case you still have issues comment back.
