### ISSUE TITLE
Helper methods not available in partials

### ISSUE THREAD

**Issue by samacs** [rails-api/rails-api#170]
Hi,

I can't to access helper methods from a controller concern in a partial view:

This is where the helper methods are defined.
```
# app/controllers/concern/user_management.rb
module UserManagement
    extend ActiveSupport::Concern
    
    included do
        helper_method :current_user, :owner?, :system_user?
    end

    protected
    # ... methods
end
```
Application controller includes the `UserManagement` concern.
```
# app/controllers/application_controller.rb
class ApplicationController < ActionController::API
    include UserManagement
end
```
This is just an specific example, but in order to reuse my views, I want to be able to access concern helper methods in partials.
```
# app/controllers/admin/accounts_controller.rb
module Admin
    class AccountsController < ApplicationController
        # ...
        def show 
        end
        # ...
        private

        def set_account
            @account = Account.find(params[:id])
        end
    end
end
```
This is the view tree:
```
app/
    views/
        accounts/
            _account.json.jbuilder
            show.json.jbuilder
        branches/
            _branch.json.jbuilder
```
Helper methods are available in views:
```
# app/views/accounts/show.json.jbuilder
#
# I can access owner? and system_user? helper methods from concern here.
#
json.account do
    json.partial! 'accounts/account', account: @account
end
```
But can't access helper methods on partials:
```
# app/views/accounts/_account.json.jbuilder
json.extract! account, :id, :name
# Account has many branches
json.branches do
    json.array! account.branches, partial: 'branches/branch', as: :branch
end
```
This is the partial where I need to make a decision based on whether the user is a system user or an owner:
```
# app/views/branches/_branch.json.jbuilder
json.extract! branch, :name
if system_user?
    json.billing_addresses do
        json.array! branch.billing_addresses, partial: 'billing_addresses/billing_address', as: :billing_address
    end
elsif owner?
    json.billing_address do
        json.partial! 'billing_addresses/billing_address', billing_address: branch.billing_addresses.find_by_account(current_user.account_id)
    end
end
```
Is it possible to execute helper methods from partials? Isn't it in the same context as the view?

Thanks in advance.

**Comment by Captain1** [comment]
@samacs
See this: http://stackoverflow.com/questions/14752935/how-to-use-view-helpers-with-rails-api-gem
Here is my application controller:
![image](https://cloud.githubusercontent.com/assets/4882809/6888623/df5175e4-d67b-11e4-9e73-dd7eabfc1af6.png)
But is there a way to import all helper method not only in my helpers directory as well as  helpers directories from other gems?I can't use helper methods from other gems now. What else should i have to import, like I set "config.api_only = false" to restore default middleware stack? My site is in a mess once not using Application::Base, like styling etc. Any further explanations?

**Comment by spastorino** [comment]
Yeah it won't work by default.
