### ISSUE TITLE
rails-api: command not found after gem install

### ISSUE THREAD

**Issue by ghost** [rails-api/rails-api#173]
after gem install,
when i run rails-api new my-app

it shows:
rails-api: command not found

how to fix it? Thanks

**Comment by oseifrimpong** [comment]
How did it work? Am having the same problem. Can anyone help me out?

**Comment by sungwon** [comment]
@oseifrimpong are you using rvm or rbenv? I use rbenv and found that I needed to run `rbenv rehash` to run the new binary.

See: http://askubuntu.com/questions/142720/cant-run-a-program-installed-through-gem-install

**Comment by varun24143** [comment]
Hi, When i m trying to run a rails command, it says -bash : rails : command not found, i m new to this can you please tell me what is to be done?

**Comment by oseifrimpong** [comment]
run "rbenv rehash". It should work.

Regards,
Obed Osei Frimpong
South China University
of Technology, Guangzhou

**Comment by varun24143** [comment]
It still shows the same error, even when i am writing
rails -v
it says rails : command not found.
How to resolve this ?

**Comment by oseifrimpong** [comment]
I am using rbenv

**Comment by KamuelaFranco** [comment]
@sungwon `rbenv rehash` was perfect. Thank you.

**Comment by patota** [comment]
rbenv rehash work!
thx

**Comment by chmatos** [comment]
run "rbenv rehash" works for me
