### ISSUE TITLE
Cut new version of the gem?

### ISSUE THREAD

**Issue by tjschuck** [rails-api/rails-api#182]
@spastorino @carlosantoniodasilva @steveklabnik Can you please cut and release a [new version](https://rubygems.org/gems/rails-api) of the gem for RubyGems?

#178/#181 would be particularly nice to have as people are moving to Rails 4.2 to silence that warning.

Thanks! :heart: :heart: :heart_eyes_cat: :heart:

**Comment by steveklabnik** [comment]
Done! 0.4.0 is out.

**Comment by spastorino** [comment]
:+1:
