### ISSUE TITLE
Is it possible to specify target directory for new applications?

### ISSUE THREAD

**Issue by stieler-it** [rails-api/rails-api#184]
With rails, I can do
`rails new appname .`
to create a new application in the current directory (without creating a subdirectory).
Is this possible with rails-api as well?

**Comment by Davidslv** [comment]
Hi @stieler-it, yes you can simply use `rails-api`

like so:

```
$ rails-api new burguershop

      create
      create  README.rdoc
      create  Rakefile
      create  config.ru
....
```

**Comment by steveklabnik** [comment]
That's not creating it in the current directory though.

**Comment by Davidslv** [comment]
@stieler-it what you looking for is actually `rails-api new .`

**Comment by spastorino** [comment]
You should be able to do the same thing in both projects, please comment back if it's still an issue.
