### ISSUE TITLE
`protect_from_forgery` like thing needed

### ISSUE THREAD

**Issue by penne12** [rails-api/rails-api#191]
I need some way to use something like `protect_from_forgery` in my api, as the browser is my client (it's an ember app).

**Comment by bmorton** [comment]
If you need `protect_from_forgery`, you probably should just use rails instead of rails-api.  You should also only need it if you're authenticating to your API via a session.  If that's what you're doing, I'd recommend switching to a token-based authentication and you'll be fine.

**Comment by penne12** [comment]
Yeah, was tired when I wrote this, I'm using token-based authentication... ugh...
