### ISSUE TITLE
User auth with Rails-API.

### ISSUE THREAD

**Issue by tritonresearch** [rails-api/rails-api#192]
Hi, I have a REST API built on top of Rails API, but now it requires user authentication. The preferred scheme is to have the user send username/password to the API and receive an auth token for subsequent calls.

Is there any recommended way of doing this with Rails API besides Devise, as Devise does not interoperate well with Rails API (see https://github.com/rails-api/rails-api/issues/24 and https://github.com/plataformatec/devise/issues/2775) and provides a bunch of unnecessary functionality for an API?

Thanks in advance,
Jake

**Comment by Davidslv** [comment]
Maybe [doorkeeper](https://github.com/doorkeeper-gem/doorkeeper) can do what you need, have a look.

**Comment by Captain1** [comment]
I use cookie to store token in order to "remember user" even if you close the browser. e.g.	
def sign_in(user)
        cookies.permanent[:remember_token] = user.remember_token
        self.current_user = user
end
In this case, protect_from_forgery from ::Base module can't be commented out if i want to use ::API.Is there a way to import protect_from_forgery?@steveklabnik

**Comment by spastorino** [comment]
I'm closing this because it's not an issue. Please discuss in the Rails API mailing list and/or IRC channel.
