### ISSUE TITLE
How to add rails-api to an existing Rails 4 project?

### ISSUE THREAD

**Issue by ginolon** [rails-api/rails-api#204]
Is there a tutorial somewhere?

Because I don't want to change my **application_controller.rb**, remove **protect_from_forgery** (because I use cookies with the existing project).

I just need to "**ADD**" rails-api to my project and have some APIs for just some controllers.

HOW TO?

**Comment by nsarno** [comment]
Rails-api is only a lightweight subset of rails, as stated in the README:

```
Rails::API is a subset of a normal Rails application, created for applications that don't require all functionality that a complete Rails application provides.
```

Thus you don't need to add rails-api to your project. You only want to use it if you're doing something like an API only application.

The only thing that is not included with a normal Rails 4 application and that you might want to add to your project (but not required at all) is [ActiveModel::Serializer](https://github.com/rails-api/active_model_serializers).

**Comment by ginolon** [comment]
Ok. Got it.
