### ISSUE TITLE
Usage in Rails

### ISSUE THREAD

**Issue by iliastsangaris** [rails-api/rails-api#205]
Given this project has been merged into Rails, is there any documentation for how `rails-api` can be used in the context of Rails?

On Rails 4.2.3 I've tried `rails new --api <app_name>` which simply generates an app named `--api`. Is the gem still the best solution until Rails 5 is fully released or is there a better intermediate solution?

**Comment by steveklabnik** [comment]
Yes, this is only in Rails 5.

http://wyeworks.com/blog/2015/6/30/how-to-build-a-rails-5-api-only-and-ember-application/

**Comment by iliastsangaris** [comment]
Great article—would be a nice addition to the readme. Thanks!
