### ISSUE TITLE
Upgrading to rails 5?

### ISSUE THREAD

**Issue by ledbettj** [rails-api/rails-api#212]
Since rails-api has been merged into Rails 5, is there any guidance for upgrading from an existing 4.2 rails-api application?

I assume the Rails upgrade guide is useful, and I see I should probably add `config.api_only = true` to my application config -- is there anything else that needs to or should be done?

Cheers!

**Comment by chemica** [comment]
There are instructions for applying the gem to an existing Rails application in the README. Did they not work for you?

**Comment by jbrukh** [comment]
+1. Would love to get some guidance on upgrading.

**Comment by aarongray** [comment]
+1. I'm in the same boat and would appreciate any insight on this topic as well.

**Comment by spastorino** [comment]
Doesn't this http://edgeguides.rubyonrails.org/api_app.html#changing-an-existing-application work for you?.
Maybe if not or if it lacks some stuff is a good starting point if any of you guys want to provide a better upgrading guide?.

Please if you want to go ahead provide PRs improving it.

**Comment by oyeanuj** [comment]
@ledbettj @jbrukh @aarongray any tips if you guys did end up upgrading? I am looking to do the same!

**Comment by oyeanuj** [comment]
FWIW, I tried upgrading and running into the following issue (might be an AMS 0.9x issue): https://github.com/rails-api/active_model_serializers/issues/1923

If anyone here has tried upgrading, and encountered this issue, I'd appreciate any help!

**Comment by aarongray** [comment]
Here's a tutorial on [Updating rails-api to Rails 5 in API mode](https://www.aaron-gray.com/updating-rails-api-to-rails-5-in-api-mode/).
