### ISSUE TITLE
Is there a way to do parameter validation and coercion like Grape?

### ISSUE THREAD

**Issue by fogisland** [rails-api/rails-api#216]
Found it a little bit hard to do parameter validation and coercion in rails-api.

Grape supplies  DSL to do these work:
https://github.com/ruby-grape/grape#parameter-validation-and-coercion

Will rails-api supply similar utilities, or there`s already some best practise? It seems that no one ever made such requirement.

**Comment by steveklabnik** [comment]
rails-api only removes excess stuff from Rails, it doesn't add anything.

Years ago, we thought about adding stuff, but it never really happened.
