### ISSUE TITLE
How to integrate the code in rails 5

### ISSUE THREAD

**Issue by ajazshaik** [rails-api/rails-api#217]
Can you tell me how to integrate the code in rails 5 app

**Comment by steveklabnik** [comment]
You don't need this gem with rails 5, as it's in rails natively. please see http://edgeguides.rubyonrails.org/api_app.html

**Comment by ajazshaik** [comment]
I have a code with me,  can you tell me where to integrate that code in my rails app
require 'net/http'
smsserver = 'http://springedge.com/'
apikey = 'A9cd9xxxxxxxxxxxxxx;'
message = 'test sms'
messagebody = URI::encode(message)
mobileno = '9199xxxxxx'
sender = 'SPEDGE'
url = URI.parse(smsserver+'?apikey='+apikey+'&sender='+sender+'&to='+mobileno+'&message='+messagebody)
req = Net::HTTP{|http|
http.Getrequest(req)
}
puts res.body
