### ISSUE TITLE
'uninitialized constant ActionController::API::RackDelegation' in rails 5.0

### ISSUE THREAD

**Issue by vedant1811** [rails-api/rails-api#218]
I get the following error for rails-api after upgrading to rails 5.0:

    Error:
        V1::UsersControllerTest#test_should_update_user:
    NameError: uninitialized constant ActionController::API::RackDelegation
    rails-api (0.4.0) lib/rails-api/action_controller/api.rb:131:in `<class:API>'
        rails-api (0.4.0) lib/rails-api/action_controller/api.rb:85:in `<module:ActionController>'
        rails-api (0.4.0) lib/rails-api/action_controller/api.rb:5:in `<top (required)>'
    rails-api (0.4.0) lib/rails-api.rb:3:in `<top (required)>'
        app/controllers/v1_controller.rb:1:in `<top (required)>'
        activesupport (5.0.0.1) lib/active_support/dependencies/interlock.rb:12:in `block in loading'
    activesupport (5.0.0.1) lib/active_support/concurrency/share_lock.rb:117:in `exclusive'
        activesupport (5.0.0.1) lib/active_support/dependencies/interlock.rb:11:in `loading'
        app/controllers/v1/users_controller.rb:1:in `<top (required)>'
    activesupport (5.0.0.1) lib/active_support/dependencies/interlock.rb:12:in `block in loading'
        activesupport (5.0.0.1) lib/active_support/concurrency/share_lock.rb:117:in `exclusive'
        activesupport (5.0.0.1) lib/active_support/dependencies/interlock.rb:11:in `loading'
    activesupport (5.0.0.1) lib/active_support/inflector/methods.rb:270:in `const_get'
        activesupport (5.0.0.1) lib/active_support/inflector/methods.rb:270:in `block in constantize'
        activesupport (5.0.0.1) lib/active_support/inflector/methods.rb:266:in `each'
    activesupport (5.0.0.1) lib/active_support/inflector/methods.rb:266:in `inject'
        activesupport (5.0.0.1) lib/active_support/inflector/methods.rb:266:in `constantize'
        activesupport (5.0.0.1) lib/active_support/inflector/methods.rb:311:in `safe_constantize'
    activesupport (5.0.0.1) lib/active_support/core_ext/string/inflections.rb:77:in `safe_constantize'
        activesupport (5.0.0.1) lib/active_support/testing/constant_lookup.rb:39:in `determine_constant_from_test_name'
        actionpack (5.0.0.1) lib/action_controller/test_case.rb:354:in `determine_default_controller_class'
    actionpack (5.0.0.1) lib/action_controller/test_case.rb:349:in `controller_class'
        actionpack (5.0.0.1) lib/action_controller/test_case.rb:582:in `setup_controller_request_and_response'
        activesupport (5.0.0.1) lib/active_support/callbacks.rb:382:in `block in make_lambda'
    activesupport (5.0.0.1) lib/active_support/callbacks.rb:169:in `call'
        activesupport (5.0.0.1) lib/active_support/callbacks.rb:169:in `block (2 levels) in halting'
        activesupport (5.0.0.1) lib/active_support/callbacks.rb:547:in `call'
    activesupport (5.0.0.1) lib/active_support/callbacks.rb:547:in `block (2 levels) in default_terminator'
        activesupport (5.0.0.1) lib/active_support/callbacks.rb:546:in `catch'
        activesupport (5.0.0.1) lib/active_support/callbacks.rb:546:in `block in default_terminator'
    activesupport (5.0.0.1) lib/active_support/callbacks.rb:170:in `call'
        activesupport (5.0.0.1) lib/active_support/callbacks.rb:170:in `block in halting'
        activesupport (5.0.0.1) lib/active_support/callbacks.rb:454:in `call'
    activesupport (5.0.0.1) lib/active_support/callbacks.rb:454:in `block in call'
        activesupport (5.0.0.1) lib/active_support/callbacks.rb:454:in `each'
        activesupport (5.0.0.1) lib/active_support/callbacks.rb:454:in `call'
    activesupport (5.0.0.1) lib/active_support/callbacks.rb:101:in `__run_callbacks__'
        activesupport (5.0.0.1) lib/active_support/callbacks.rb:750:in `_run_setup_callbacks'
        activesupport (5.0.0.1) lib/active_support/callbacks.rb:90:in `run_callbacks'
    activesupport (5.0.0.1) lib/active_support/testing/setup_and_teardown.rb:41:in `before_setup'
        activerecord (5.0.0.1) lib/active_record/fixtures.rb:853:in `before_setup'
        railties (5.0.0.1) lib/rails/test_help.rb:33:in `before_setup'
    minitest (5.9.0) lib/minitest/test.rb:105:in `block (3 levels) in run'
        minitest (5.9.0) lib/minitest/test.rb:204:in `capture_exceptions'
        minitest (5.9.0) lib/minitest/test.rb:104:in `block (2 levels) in run'
    minitest (5.9.0) lib/minitest/test.rb:255:in `time_it'
        minitest (5.9.0) lib/minitest/test.rb:103:in `block in run'
        minitest (5.9.0) lib/minitest.rb:348:in `on_signal'
    minitest (5.9.0) lib/minitest/test.rb:275:in `with_info_handler'
        minitest (5.9.0) lib/minitest/test.rb:102:in `run'
        minitest (5.9.0) lib/minitest.rb:799:in `run_one_method'
    minitest (5.9.0) lib/minitest.rb:322:in `run_one_method'
        minitest (5.9.0) lib/minitest.rb:310:in `block (2 levels) in run'
        minitest (5.9.0) lib/minitest.rb:309:in `each'
    minitest (5.9.0) lib/minitest.rb:309:in `block in run'
        minitest (5.9.0) lib/minitest.rb:348:in `on_signal'
        minitest (5.9.0) lib/minitest.rb:335:in `with_info_handler'
    minitest (5.9.0) lib/minitest.rb:308:in `run'
        railties (5.0.0.1) lib/rails/test_unit/line_filtering.rb:11:in `run'
        minitest (5.9.0) lib/minitest.rb:158:in `block in __run'
    minitest (5.9.0) lib/minitest.rb:158:in `map'
        minitest (5.9.0) lib/minitest.rb:158:in `__run'
        minitest (5.9.0) lib/minitest.rb:135:in `run'
    railties (5.0.0.1) lib/rails/commands/test.rb:9:in `<top (required)>'
        railties (5.0.0.1) lib/rails/commands/commands_tasks.rb:138:in `require'
        railties (5.0.0.1) lib/rails/commands/commands_tasks.rb:138:in `require_command!'
    railties (5.0.0.1) lib/rails/commands/commands_tasks.rb:95:in `test'
        railties (5.0.0.1) lib/rails/commands/commands_tasks.rb:49:in `run_command!'
        railties (5.0.0.1) lib/rails/commands.rb:18:in `<top (required)>'
    bin/rails:4:in `require'
        bin/rails:4:in `<main>'

More information here: https://gist.github.com/vedant1811/ff1626fb66deb8829e72e4a43c1ada3a

**Comment by spastorino** [comment]
You shouldn't be using this gem with Rails 5. Rails 5 already has rails-api merged in. So rails-api (this gem) and Rails 5 are not compatible you should just remove rails-api from the Gemfile.
