### ISSUE TITLE
Render JSON seems broken it keeps return HTML

### ISSUE THREAD

**Issue by HotDudeSmith** [rails-api/rails-api#219]
I am new to build Rails API from scratch (only API not web app) so I can build iOS app to connect to API. What I have an issue on my Rails API project doesn't allow me to have return JSON results, it always return HTML. Any idea what is wrong? Any suggestion appreciated. Thanks!

What I want to have a return in JSON like this:
`{"code":12,"title":"User doesn't exist","status":404}`

This is what I got (it returns in red header in HTML page):
![image](https://cloud.githubusercontent.com/assets/22647256/19132347/a52b81b8-8b18-11e6-9726-9f27670945f8.png)

Take a look at my scripts:

**routes.rb** (require JSON format):
```
Rails.application.routes.draw do

  namespace :api, defaults: { format: :json } do 
    namespace :v1 do
      resources :entries, except: [:new, :edit]
      resources :users, except: [:new, :edit]
    end
  end

end
```
<br>

**../app/controllers/api/v1/users_controller.rb**
```
module Api
  module V1
    class UsersController < ApplicationController

      before_action :set_user, only: [:show, :update, :destroy]

      def show
        if User.exists?(params[:id])
          @user = User.find(params[:id])
          render json: @user
        else 
          render json: { code: 12, title: "User doesn't exist", status: 404 }, status: :not_found
      end 
 .
 .
 .
```

### Note: It is very strange how this _show_ method above acting weird. Part 1 is working well to return JSON results but Part 2 returns HTML instead JSON results.
Part 1: `render json: @user`

Part 2:  `render json: { code: 12, title: "User doesn't exist", status: 404 }, status: :not_found`

<br>

**../app/controllers/api/v1/application_controller.rb**
```
class ApplicationController < ActionController::API

rescue_from ActionController::ParameterMissing, with: :render_bad_request  
rescue_from ActiveRecord::RecordNotSaved, :with => :access_denied

  def render_bad_request(e)
    render json: params, status: :bad_request
  end

end
```

**Comment by pboling** [comment]
@HotDudeSmith See the first line of the Readme.

> IMPORTANT: Rails::API has been merged into Rails

You should not be using this project.  You should use regular rails gem, and use the `api` flag to setup an API-only application.

There is an official guide about how to do this in a canonical manner:
http://edgeguides.rubyonrails.org/api_app.html

**Comment by HotDudeSmith** [comment]
@pboling Oh, I didn't see this news. Thanks for letting me know about it. Do I need to remove `gem "active_model_serializers", "~> 0.10.0"` from my gem file also? I wanted to use only API not web app.

**Comment by pboling** [comment]
No you still need it, unless you are going to use something else to represent your objects as JSON (and there are other alternatives that *I* would choose over active model serializers).

Here are a few blog posts to get you started:

* https://medium.com/@lukeghenco/how-to-use-rails-5-api-only-mode-part-1-dbefccf18bad#.vw7yjxtgy
* https://hashrocket.com/blog/posts/how-to-make-rails-5-api-only
* https://www.simplify.ba/articles/2016/06/18/creating-rails5-api-only-application-following-jsonapi-specification/

**Comment by HotDudeSmith** [comment]
@pboling Thank you for the info.

**Comment by pboling** [comment]
@HotDudeSmith Happy to help.
