### ISSUE TITLE
How much of a performance impact when switching from rails to rails-api ?

### ISSUE THREAD

**Issue by jatindhankhar** [rails-api/rails-api#228]
We recently started migrating one of the micro service that handles a lot of traffic (17.7k RPM  avg)  from standard rails to rails api and routed 10% of the traffic to that box and monitored for more than 24 hours.
Sadly, We see no change in any of the metrics nor any improve in performance. 

`rake middleware` does say we have less middle wares but this doesn't translate when it comes to metrics. 
Following middlewares were removed 

```ruby
use Rack::MethodOverride
use ActionDispatch::Cookies
use ActionDispatch::Session::CookieStore
use ActionDispatch::Flash
use ActionDispatch::ContentSecurityPolicy::Middleware
use Rack::TempfileReaper
```

1. Memory
2. Response time 
3. CPU usage 

all are same to those boxes which run full rails app.

Our app didn't use views at all from the start, it only responded in json only. 
Now, we just switched it to rails-api only and we don't see any impact. 
Is it due to the fact that views were not used, so no impact. ?

At least removing middleware should have made some impact. 

Are we missing something ?

**Comment by rafaelfranca** [comment]
What you observed is true. Using Rails api should have no noticeable performance impact in the app. Removing middleware may have performance impact in micro benchmarks, but not in real scenarios.

**Comment by jatindhankhar** [comment]
Great, thanks for the clarification. 
We were under the impression that cutting down on middleware may lead to some improvements. 
[Even the official docs, don't mention anything about performance.](https://guides.rubyonrails.org/api_app.html)
 
Any other change we can do to improve performance ? 


Maybe the docs should mention that switching won't improve performance in real life scenarios.

So what is the benefit of migration an existing app to api only, if not for performance ?
