### ISSUE TITLE
Caching issue

### ISSUE THREAD

**Issue by jocubeit** [rails-api/rails-api#25]
What do I need to add back in to get `caches_page` and `cache_sweeper` working in a controller? The error I'm receiving is:

```
ActionController::RoutingError (undefined method `caches_page' for WidgetsController:Class)
```

My controller looks like this:

``` ruby

class WidgetsController < ApplicationController

  caches_page :index, :show
  before_filter(only: [:index, :show]) { @page_caching = true }
  cache_sweeper :widget_sweeper

  # actions omitted

end
```

I'm using `memcached` and the `dalli` gem for the `cache_store` and `session_store`, which is working beautifully in a regular ActionController::Base project.

**Comment by trkoch** [comment]
I just stumbled upon this very issue. Including `ActionController::Caching` in the `ApplicationController` makes caching work. However it is now enabled regardless of the environment settings, breaking my tests. What is the recommended approach here?
