### ISSUE TITLE
ActionController::ParamsWrapper is not on by default

### ISSUE THREAD

**Issue by jerodsanto** [rails-api/rails-api#33]
The generated `config/initializers/wrap_parameters` files says that `ActionController::ParamsWrapper` is enabled by default, but it is not.

Perhaps it _should_ be enabled by default, because when consuming JSON requests its pretty nice to not require the root object. If that's not going to happen, the generator should be modified so that it states that this module is disabled by default.

**Comment by LucasSubli** [comment]
Using an rails-api generated (v0.4.0) the generated code in config/initializers/wrap_parameters.rb has the respond_to in there as expected but... it does not work. Had to go with @cimm fix.

If i got the discussion right it shouldn`t be the case. Am i missing something?

**Comment by abrisse** [comment]
+1 with @LucasSubli
