### ISSUE TITLE
disabled asset_host?

### ISSUE THREAD

**Issue by michaelirey** [rails-api/rails-api#36]
What would one have to do in order to use (development.rb):
`config.action_controller.asset_host`

I am not really using assets but it would be nice to use `image_tag` which should normally use `config.action_controller.asset_host`, but I believe this gem disables it somehow.

Any ideas?

**Comment by lulalalalistia** [comment]
http://stackoverflow.com/questions/11697266/rails-3-2-7-override-image-tag-for-asset-host relevant SO question
