### ISSUE TITLE
Using rails-api as an isolated engine

### ISSUE THREAD

**Issue by mattiassvedhem** [rails-api/rails-api#41]
Using rails-api as an isolated engine and mounting it in a normal rails application I'm getting this error

```
wrong argument type Module (expected Class)
```

with this code

```
module Api
  class ApplicationController < ActionController::API
  end
end
```

And the trace gives me this:

```
app/controllers/api/application_controller.rb:2:in `<module:Api>'
```

Somehow it seems like it expects the wrapping module to be a class. However switching to ActionController::Base solves it. Any idea why? Maybe I'm missing some controller module that's needed for that to work?

Thanks!

**Comment by webattitude** [comment]
same problem now, but the required class is not found : 
```
cannot load such file -- rails-api/action_controller/api
```

**Comment by webattitude** [comment]
Ok problem solved. Dependencies have to be set in gemspec file.
