### ISSUE TITLE
Breaks secure_session_store in Rails 4

### ISSUE THREAD

**Issue by ollym** [rails-api/rails-api#73]
Don't ask me how or why but I was using 

9ad1575bbe114319de1fbf4c4eb7f552e1052b8c

And it worked perfectly. A simple bundle update to 

45abe612453e92a06eb7e28927f7cb02b42add5c

And my rails application stops setting the session cookie and all hell broke loose.

**Comment by grantgeorge** [comment]
@lgs that helped - thank you
