### ISSUE TITLE
NoMethodError (undefined method `default_render' for #<Api::RegistrationsController:0x0000000575c718>):

### ISSUE THREAD

**Issue by astronaute77** [rails-api/rails-api#93]
Hi,

 I'm getting the `undefined method 'default_render'` error when trying to output json over `respond_with` using `ActionController::API` on Rails 4:

``` ruby
class Api::RegistrationsController < ActionController::API
  include ActionController::MimeResponds
  respond_to :json

  def create
    hello = { hello: "world" }
    respond_with(hello, location: "/something")
  end

end
```

It works as expected if extending `ActionController::Base` instead.

I'm just playing with rails-api so maybe I'm doing something wrong :)

Cheers!

**Comment by Amrzohdi** [comment]
that worked thank you
